% Jorge | 2016-09-26
% 
% Test script for dynamic optimization solver.  Used to expedite C code generation.
% 
% 


clear
clc

load('solve_dynamic_optimization_freeze.mat')

birthyear = -45;

[V, Vss, kopt, koptss, labopt, bopt, ...
 fedincome, fedincomess, ...
 fitax,     fitaxss,     ...
 fsstax,    fsstaxss,    ...
 fcaptax,   fcaptaxss]   ...
 ...
   = solve_dynamic_optimization(...
       beq*ones(1,Tss), T, Tr, Tss, birthyear, ...
       bgrid, kgrid, nb, nk, nz, idem, ...
       mpci, rpci, cap_tax_share, ss_tax_cred, ...
       surv, tau_cap, tau_capgain, tau_ss*ones(1,Tss), tr_z, v_ss_max*ones(1,Tss), z, ...
       wage*ones(1,Tss), cap_share*ones(1,Tss), debt_share*ones(1,Tss), rate_cap*ones(1,Tss), rate_gov*ones(1,Tss), rate_tot*ones(1,Tss), cap_inc*ones(1,Tss), exp_subsidys, q_tobin, q_tobin, Vbeq, ...
       avg_deduc, clinton, coefs, limit, X, ben*ones(1,Tss), ...
       beta, gamma, sigma);